import { ThemeConfigProvider } from "@/shared/providers/theme-config-provider"
import type { Metadata } from "next"
import { ThemeProvider } from "next-themes"
import localFont from "next/font/local"
import type { ReactNode } from "react"

import "./globals.css"
import { TmaSdkProvider } from "@/shared/providers/tma-sdk-provider"

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
})

const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

type LayoutProps = {
  children: ReactNode
}

export default function Layout({ children }: LayoutProps) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${geistMono.variable} ${geistSans.variable}`}>
        <TmaSdkProvider>
          <ThemeProvider>
            <ThemeConfigProvider>{children}</ThemeConfigProvider>
          </ThemeProvider>
        </TmaSdkProvider>
      </body>
    </html>
  )
}
