import type { Metadata } from "next"
import Script from "next/script"
import type { ReactNode } from "react"

import "./globals.css"

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

type LayoutProps = {
  children: ReactNode
}

export default function Layout({ children }: LayoutProps) {
  return (
    <html lang="en">
      <body>
        <Script src="https://telegram.org/js/telegram-web-app.js" />
        {children}
      </body>
    </html>
  )
}
