/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteRouteImport } from './routes/_app/route'
import { Route as LegacyDomainRouteImport } from './routes/legacy-domain'
import { Route as RpcRouteImport } from './routes/rpc'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AppMapRouteImport } from './routes/_app/map'
import { Route as AppOnboardingRouteImport } from './routes/_app/onboarding'
import { Route as AppPremiumRouteImport } from './routes/_app/premium'
import { Route as AuthTelegramRouteImport } from './routes/auth/telegram'
import { Route as AuthVkRouteImport } from './routes/auth/vk'
import { Route as RpcSplatRouteImport } from './routes/rpc/$'
import { Route as AppEventsIndexRouteImport } from './routes/_app/events/index'
import { Route as AppEventsNewRouteImport } from './routes/_app/events/new'
import { Route as AppHomeworkIndexRouteImport } from './routes/_app/homework/index'
import { Route as AppHomeworkIdRouteImport } from './routes/_app/homework/$id'
import { Route as AppHomeworkAddRouteImport } from './routes/_app/homework/add'
import { Route as AppScheduleGroupIdRouteImport } from './routes/_app/schedule/$groupId'
import { Route as AppSettingsIndexRouteImport } from './routes/_app/settings/index'
import { Route as AppSettingsAdminRouteImport } from './routes/_app/settings/admin'
import { Route as AppSettingsMapRouteImport } from './routes/_app/settings/map'
import { Route as AppEventsIdEditRouteImport } from './routes/_app/events/$id/edit'

const AppRouteRoute = AppRouteRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const LegacyDomainRoute = LegacyDomainRouteImport.update({
  id: '/legacy-domain',
  path: '/legacy-domain',
  getParentRoute: () => rootRouteImport,
} as any)
const RpcRoute = RpcRouteImport.update({
  id: '/rpc',
  path: '/rpc',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppMapRoute = AppMapRouteImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppOnboardingRoute = AppOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppPremiumRoute = AppPremiumRouteImport.update({
  id: '/premium',
  path: '/premium',
  getParentRoute: () => AppRouteRoute,
} as any)
const AuthTelegramRoute = AuthTelegramRouteImport.update({
  id: '/auth/telegram',
  path: '/auth/telegram',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthVkRoute = AuthVkRouteImport.update({
  id: '/auth/vk',
  path: '/auth/vk',
  getParentRoute: () => rootRouteImport,
} as any)
const RpcSplatRoute = RpcSplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => RpcRoute,
} as any)
const AppEventsIndexRoute = AppEventsIndexRouteImport.update({
  id: '/events/',
  path: '/events/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppEventsNewRoute = AppEventsNewRouteImport.update({
  id: '/events/new',
  path: '/events/new',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppHomeworkIndexRoute = AppHomeworkIndexRouteImport.update({
  id: '/homework/',
  path: '/homework/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppHomeworkIdRoute = AppHomeworkIdRouteImport.update({
  id: '/homework/$id',
  path: '/homework/$id',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppHomeworkAddRoute = AppHomeworkAddRouteImport.update({
  id: '/homework/add',
  path: '/homework/add',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppScheduleGroupIdRoute = AppScheduleGroupIdRouteImport.update({
  id: '/schedule/$groupId',
  path: '/schedule/$groupId',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppSettingsIndexRoute = AppSettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppSettingsAdminRoute = AppSettingsAdminRouteImport.update({
  id: '/settings/admin',
  path: '/settings/admin',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppSettingsMapRoute = AppSettingsMapRouteImport.update({
  id: '/settings/map',
  path: '/settings/map',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppEventsIdEditRoute = AppEventsIdEditRouteImport.update({
  id: '/events/$id/edit',
  path: '/events/$id/edit',
  getParentRoute: () => AppRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/legacy-domain': typeof LegacyDomainRoute
  '/rpc': typeof RpcRouteWithChildren
  '/map': typeof AppMapRoute
  '/onboarding': typeof AppOnboardingRoute
  '/premium': typeof AppPremiumRoute
  '/auth/telegram': typeof AuthTelegramRoute
  '/auth/vk': typeof AuthVkRoute
  '/rpc/$': typeof RpcSplatRoute
  '/events/new': typeof AppEventsNewRoute
  '/homework/$id': typeof AppHomeworkIdRoute
  '/homework/add': typeof AppHomeworkAddRoute
  '/schedule/$groupId': typeof AppScheduleGroupIdRoute
  '/settings/admin': typeof AppSettingsAdminRoute
  '/settings/map': typeof AppSettingsMapRoute
  '/events/': typeof AppEventsIndexRoute
  '/homework/': typeof AppHomeworkIndexRoute
  '/settings/': typeof AppSettingsIndexRoute
  '/events/$id/edit': typeof AppEventsIdEditRoute
}
export interface FileRoutesByTo {
  '/legacy-domain': typeof LegacyDomainRoute
  '/rpc': typeof RpcRouteWithChildren
  '/map': typeof AppMapRoute
  '/onboarding': typeof AppOnboardingRoute
  '/premium': typeof AppPremiumRoute
  '/auth/telegram': typeof AuthTelegramRoute
  '/auth/vk': typeof AuthVkRoute
  '/rpc/$': typeof RpcSplatRoute
  '/': typeof AppIndexRoute
  '/events/new': typeof AppEventsNewRoute
  '/homework/$id': typeof AppHomeworkIdRoute
  '/homework/add': typeof AppHomeworkAddRoute
  '/schedule/$groupId': typeof AppScheduleGroupIdRoute
  '/settings/admin': typeof AppSettingsAdminRoute
  '/settings/map': typeof AppSettingsMapRoute
  '/events': typeof AppEventsIndexRoute
  '/homework': typeof AppHomeworkIndexRoute
  '/settings': typeof AppSettingsIndexRoute
  '/events/$id/edit': typeof AppEventsIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteRouteWithChildren
  '/legacy-domain': typeof LegacyDomainRoute
  '/rpc': typeof RpcRouteWithChildren
  '/_app/map': typeof AppMapRoute
  '/_app/onboarding': typeof AppOnboardingRoute
  '/_app/premium': typeof AppPremiumRoute
  '/auth/telegram': typeof AuthTelegramRoute
  '/auth/vk': typeof AuthVkRoute
  '/rpc/$': typeof RpcSplatRoute
  '/_app/': typeof AppIndexRoute
  '/_app/events/new': typeof AppEventsNewRoute
  '/_app/homework/$id': typeof AppHomeworkIdRoute
  '/_app/homework/add': typeof AppHomeworkAddRoute
  '/_app/schedule/$groupId': typeof AppScheduleGroupIdRoute
  '/_app/settings/admin': typeof AppSettingsAdminRoute
  '/_app/settings/map': typeof AppSettingsMapRoute
  '/_app/events/': typeof AppEventsIndexRoute
  '/_app/homework/': typeof AppHomeworkIndexRoute
  '/_app/settings/': typeof AppSettingsIndexRoute
  '/_app/events/$id/edit': typeof AppEventsIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/legacy-domain'
    | '/rpc'
    | '/map'
    | '/onboarding'
    | '/premium'
    | '/auth/telegram'
    | '/auth/vk'
    | '/rpc/$'
    | '/events/new'
    | '/homework/$id'
    | '/homework/add'
    | '/schedule/$groupId'
    | '/settings/admin'
    | '/settings/map'
    | '/events/'
    | '/homework/'
    | '/settings/'
    | '/events/$id/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/legacy-domain'
    | '/rpc'
    | '/map'
    | '/onboarding'
    | '/premium'
    | '/auth/telegram'
    | '/auth/vk'
    | '/rpc/$'
    | '/'
    | '/events/new'
    | '/homework/$id'
    | '/homework/add'
    | '/schedule/$groupId'
    | '/settings/admin'
    | '/settings/map'
    | '/events'
    | '/homework'
    | '/settings'
    | '/events/$id/edit'
  id:
    | '__root__'
    | '/_app'
    | '/legacy-domain'
    | '/rpc'
    | '/_app/map'
    | '/_app/onboarding'
    | '/_app/premium'
    | '/auth/telegram'
    | '/auth/vk'
    | '/rpc/$'
    | '/_app/'
    | '/_app/events/new'
    | '/_app/homework/$id'
    | '/_app/homework/add'
    | '/_app/schedule/$groupId'
    | '/_app/settings/admin'
    | '/_app/settings/map'
    | '/_app/events/'
    | '/_app/homework/'
    | '/_app/settings/'
    | '/_app/events/$id/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRouteRoute: typeof AppRouteRouteWithChildren
  LegacyDomainRoute: typeof LegacyDomainRoute
  RpcRoute: typeof RpcRouteWithChildren
  AuthTelegramRoute: typeof AuthTelegramRoute
  AuthVkRoute: typeof AuthVkRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legacy-domain': {
      id: '/legacy-domain'
      path: '/legacy-domain'
      fullPath: '/legacy-domain'
      preLoaderRoute: typeof LegacyDomainRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rpc': {
      id: '/rpc'
      path: '/rpc'
      fullPath: '/rpc'
      preLoaderRoute: typeof RpcRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/map': {
      id: '/_app/map'
      path: '/map'
      fullPath: '/map'
      preLoaderRoute: typeof AppMapRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/onboarding': {
      id: '/_app/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AppOnboardingRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/premium': {
      id: '/_app/premium'
      path: '/premium'
      fullPath: '/premium'
      preLoaderRoute: typeof AppPremiumRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/auth/telegram': {
      id: '/auth/telegram'
      path: '/auth/telegram'
      fullPath: '/auth/telegram'
      preLoaderRoute: typeof AuthTelegramRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/vk': {
      id: '/auth/vk'
      path: '/auth/vk'
      fullPath: '/auth/vk'
      preLoaderRoute: typeof AuthVkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rpc/$': {
      id: '/rpc/$'
      path: '/$'
      fullPath: '/rpc/$'
      preLoaderRoute: typeof RpcSplatRouteImport
      parentRoute: typeof RpcRoute
    }
    '/_app/events/': {
      id: '/_app/events/'
      path: '/events'
      fullPath: '/events/'
      preLoaderRoute: typeof AppEventsIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/events/new': {
      id: '/_app/events/new'
      path: '/events/new'
      fullPath: '/events/new'
      preLoaderRoute: typeof AppEventsNewRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/homework/': {
      id: '/_app/homework/'
      path: '/homework'
      fullPath: '/homework/'
      preLoaderRoute: typeof AppHomeworkIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/homework/$id': {
      id: '/_app/homework/$id'
      path: '/homework/$id'
      fullPath: '/homework/$id'
      preLoaderRoute: typeof AppHomeworkIdRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/homework/add': {
      id: '/_app/homework/add'
      path: '/homework/add'
      fullPath: '/homework/add'
      preLoaderRoute: typeof AppHomeworkAddRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/schedule/$groupId': {
      id: '/_app/schedule/$groupId'
      path: '/schedule/$groupId'
      fullPath: '/schedule/$groupId'
      preLoaderRoute: typeof AppScheduleGroupIdRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/settings/': {
      id: '/_app/settings/'
      path: '/settings'
      fullPath: '/settings/'
      preLoaderRoute: typeof AppSettingsIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/settings/admin': {
      id: '/_app/settings/admin'
      path: '/settings/admin'
      fullPath: '/settings/admin'
      preLoaderRoute: typeof AppSettingsAdminRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/settings/map': {
      id: '/_app/settings/map'
      path: '/settings/map'
      fullPath: '/settings/map'
      preLoaderRoute: typeof AppSettingsMapRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/events/$id/edit': {
      id: '/_app/events/$id/edit'
      path: '/events/$id/edit'
      fullPath: '/events/$id/edit'
      preLoaderRoute: typeof AppEventsIdEditRouteImport
      parentRoute: typeof AppRouteRoute
    }
  }
}

interface AppRouteRouteChildren {
  AppMapRoute: typeof AppMapRoute
  AppOnboardingRoute: typeof AppOnboardingRoute
  AppPremiumRoute: typeof AppPremiumRoute
  AppIndexRoute: typeof AppIndexRoute
  AppEventsNewRoute: typeof AppEventsNewRoute
  AppHomeworkIdRoute: typeof AppHomeworkIdRoute
  AppHomeworkAddRoute: typeof AppHomeworkAddRoute
  AppScheduleGroupIdRoute: typeof AppScheduleGroupIdRoute
  AppSettingsAdminRoute: typeof AppSettingsAdminRoute
  AppSettingsMapRoute: typeof AppSettingsMapRoute
  AppEventsIndexRoute: typeof AppEventsIndexRoute
  AppHomeworkIndexRoute: typeof AppHomeworkIndexRoute
  AppSettingsIndexRoute: typeof AppSettingsIndexRoute
  AppEventsIdEditRoute: typeof AppEventsIdEditRoute
}

const AppRouteRouteChildren: AppRouteRouteChildren = {
  AppMapRoute: AppMapRoute,
  AppOnboardingRoute: AppOnboardingRoute,
  AppPremiumRoute: AppPremiumRoute,
  AppIndexRoute: AppIndexRoute,
  AppEventsNewRoute: AppEventsNewRoute,
  AppHomeworkIdRoute: AppHomeworkIdRoute,
  AppHomeworkAddRoute: AppHomeworkAddRoute,
  AppScheduleGroupIdRoute: AppScheduleGroupIdRoute,
  AppSettingsAdminRoute: AppSettingsAdminRoute,
  AppSettingsMapRoute: AppSettingsMapRoute,
  AppEventsIndexRoute: AppEventsIndexRoute,
  AppHomeworkIndexRoute: AppHomeworkIndexRoute,
  AppSettingsIndexRoute: AppSettingsIndexRoute,
  AppEventsIdEditRoute: AppEventsIdEditRoute,
}

const AppRouteRouteWithChildren = AppRouteRoute._addFileChildren(
  AppRouteRouteChildren,
)

interface RpcRouteChildren {
  RpcSplatRoute: typeof RpcSplatRoute
}

const RpcRouteChildren: RpcRouteChildren = {
  RpcSplatRoute: RpcSplatRoute,
}

const RpcRouteWithChildren = RpcRoute._addFileChildren(RpcRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRouteRoute: AppRouteRouteWithChildren,
  LegacyDomainRoute: LegacyDomainRoute,
  RpcRoute: RpcRouteWithChildren,
  AuthTelegramRoute: AuthTelegramRoute,
  AuthVkRoute: AuthVkRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
