import { geistMono, geistSans } from "@/app/(app)/fonts"
import Providers from "@/app/(app)/providers"
import cn from "@/shared/utils/cn"
import type { Metadata } from "next"
import type { ReactNode } from "react"
import "./globals.css"
import { NextIntlClientProvider } from "next-intl"
import { getLocale, getMessages } from "next-intl/server"

// TODO: update title and description
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

type LayoutProps = {
  children: ReactNode
}

export default async function Layout({ children }: LayoutProps) {
  const messages = await getMessages()
  const locale = await getLocale()

  return (
    <html lang={locale} suppressHydrationWarning>
      <body
        className={cn(geistMono.variable, geistSans.variable)}
        suppressHydrationWarning
      >
        <NextIntlClientProvider messages={messages}>
          <Providers>{children}</Providers>
        </NextIntlClientProvider>
      </body>
    </html>
  )
}
